CREATE OR REPLACE VIEW V_TASK AS
  SELECT
    DEVELOPMENT_CODE TASK_CODE,
    TITLE,
    OBJECT_CODE,
    'D' TASK_TYPE
  FROM T_DEVELOPMENT
  UNION
  SELECT
    TESTING_CODE TASK_CODE,
    TITLE,
    OBJECT_CODE,
    'T' TASK_TYPE
  FROM T_TESTING
  UNION
  SELECT
    MODIFICATION_CODE,
    TITLE,
    OBJECT_CODE,
    'M' TASK_TYPE
  FROM T_MODIFICATION